### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by T1MOXA** [L-EARN/NoCheatZ-4#160]
```
checking whether we are cross compiling... configure: error: in `/mnt/c/cygwin/home/T1MOXA/NoCheatZ-4/server-plugin/SourceSdk/Interfaces/Protobuf/protobuf-2.5.0':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
Building protobuf 2.5.0
make[2]: Entering directory '/mnt/c/cygwin/home/T1MOXA/NoCheatZ-4/server-plugin/SourceSdk/Interfaces/Protobuf/protobuf-2.5.0'
make[2]: *** No targets specified and no makefile found.  Stop.
make[2]: Leaving directory '/mnt/c/cygwin/home/T1MOXA/NoCheatZ-4/server-plugin/SourceSdk/Interfaces/Protobuf/protobuf-2.5.0'
Makefile:183: recipe for target 'prepare-build' failed
make[1]: *** [prepare-build] Error 2
make[1]: Leaving directory '/mnt/c/cygwin/home/T1MOXA/NoCheatZ-4/server-plugin'
Makefile:147: recipe for target 'release' failed
make: *** [release] Error 2
```

I have already installed
https://github.com/L-EARN/SourceSdk-ServerPlugin
and use "release CXX=g++-4.8" to compile
config.log - https://kopy.io/qt5qK#MnKIDJkUEQOC6Z

**Comment by T1MOXA** [comment]
When installing packages was error "Package ia32-libs is not available,"
Maybe that's the problem.

**Comment by L-EARN** [comment]
For the little story, I just broke my ubuntu computer (power-loss) while making the r9 .
I had to setup a distant server to build and I noticed this error.
Even though I did not installed those packages and the server was x64, the build went ok.

So thats not the problem. I don't know what is the problem ... I'm not sure I could help you better.

**Comment by T1MOXA** [comment]
Can write step by step how to prepare a net server for compilation ?

**Comment by L-EARN** [comment]
Took from my bash_history : 

```
dpkg --add-architecture i386
apt-get update
apt-get upgrade
apt-get install git g++ g++-multilib build-essential lib32gcc1 libc6-i386 libc6-dev-i386 autotools-dev autoconf libtool g++-4.8 g++-4.8-multilib
mkdir github
cd github/
git clone git://github.com/L-EARN/NoCheatZ-4.git
cd NoCheatZ-4
git submodule update --init
cd server-plugin/
make debug CXX=g++-4.8
make release CXX=g++-4.8
```

Downloaded the builds using sftp.

**Comment by T1MOXA** [comment]
Same error :(
```
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/root/github/NoCheatZ-4/server-plugin/SourceSdk/Interfaces/Protobuf/protobuf-2.5.0':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
Building protobuf 2.5.0
make[2]: Entering directory '/root/github/NoCheatZ-4/server-plugin/SourceSdk/Interfaces/Protobuf/protobuf-2.5.0'
make[2]: *** No targets specified and no makefile found.  Stop.
make[2]: Leaving directory '/root/github/NoCheatZ-4/server-plugin/SourceSdk/Interfaces/Protobuf/protobuf-2.5.0'
Makefile:183: recipe for target 'prepare-build' failed
make[1]: *** [prepare-build] Error 2
make[1]: Leaving directory '/root/github/NoCheatZ-4/server-plugin'
Makefile:151: recipe for target 'debug' failed
make: *** [debug] Error 2
```
(on new server)

**Comment by L-EARN** [comment]
Can I have the output of `uname -a` ?

**Comment by T1MOXA** [comment]
Linux T1MOXA-DESKTOP 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by L-EARN** [comment]
Can you look in your antivirus if something like a.exe has been deleted or not ?

**Comment by T1MOXA** [comment]
It seems not, but I can try to disable it and re-compile

**Comment by T1MOXA** [comment]
By the way, under Windows, compiles fine

**Comment by T1MOXA** [comment]
Loool
I was able to compile on my virtual server...
WTF ?

Maybe we should write in https://github.com/Microsoft/BashOnWindows/issues
so they fixed the problem ?

**Comment by L-EARN** [comment]
Give them a break. Near 1 thousand open issues :S 

But I'm not so sure this problem comes from them. For one reason or another the configure script failed to run a program, maybe there was some more settings to give for this particular scenario.

**Comment by T1MOXA** [comment]
And you can't check ?

**Comment by T1MOXA** [comment]
By the way, how to enable log in the admin chat ?

**Comment by L-EARN** [comment]
Hi,

Please try again with a fresh install of the repository.

**Comment by T1MOXA** [comment]
How to do it ?

git clone ?

**Comment by L-EARN** [comment]
Better delete everything and clone again.

But `git pull` followed by `git submodule update --init --force` should be enough, if you're using git.

**Comment by T1MOXA** [comment]
```
root@T1MOXA-DESKTOP:~/github/NoCheatZ-4/server-plugin# make release CXX=g++-4.8
make[1]: Entering directory '/root/github/NoCheatZ-4/server-plugin'
mkdir -p ../Builds/Release/addons/NoCheatZ/
mkdir -p ../Builds/Release/cfg/
mkdir -p ../Builds/Release/logs/NoCheatZ_4_Logs/
mkdir -p ../Builds/Release/NoCheatZ-autorecords
cp ./Res/nocheatz.vdf ../Builds/Release/addons/
cp ./Res/config.ini ../Builds/Release/addons/NoCheatZ/
cp ./Res/nocheatz.cfg ../Builds/Release/cfg/nocheatz.cfg ;true
cat ./Code/version.cpp
cat: ./Code/version.cpp: No such file or directory
Makefile:180: recipe for target 'prepare-build' failed
make[1]: *** [prepare-build] Error 1
make[1]: Leaving directory '/root/github/NoCheatZ-4/server-plugin'
Makefile:144: recipe for target 'release' failed
make: *** [release] Error 2
```

**Comment by L-EARN** [comment]
Oh yeah there have been some changes to the build process.

Now you need to have python 3 installed and run version.py before build, so it will create the version.cpp file using git.

Now to build the plugin you have to do : 

```
cd scripts
python version.py
cd ../server-plugin
sh ../scripts/make-protobuf.sh
make debug CXX=g++-4.8
make release CXX=g++-4.8
```

**Comment by T1MOXA** [comment]
What directory it should be done ?

**Comment by T1MOXA** [comment]
root@T1MOXA-DESKTOP:~/github/NoCheatZ-4/scripts# python version.py
#include "version.h"

char const * const NCZ_VERSION_GIT = "v4-r54-0-gf94570c";
char const * const NCZ_VERSION_GIT_SHORT = "v4-r54";


Traceback (most recent call last):
  File "version.py", line 19, in <module>
    with open("../server-plugin/Code/version.cpp", "w") as outfile:
IOError: [Errno 5] Input/output error: '../server-plugin/Code/version.cpp'

**Comment by L-EARN** [comment]
Hmmm ... do you have write permission in the directory ? Enough disk space left ?

**Comment by T1MOXA** [comment]
drwxrwxrwx 0 root root   512 Jul 29 12:55 Code

Filesystem      1K-blocks       Used Available Use% Mounted on
root            242870352  222000296  20870056  92% /root

**Comment by L-EARN** [comment]
Well. We never know, you might try again it maybe it will work.
If not, just copy this in version.cpp : 

```
#include "version.h"

char const * const NCZ_VERSION_GIT = "v4-r54-0-gf94570c";
char const * const NCZ_VERSION_GIT_SHORT = "v4-r54";
```

It's just what version.py is meant to do. But if it doesn't work on your subsystem ...

**Comment by T1MOXA** [comment]
```
root@T1MOXA-DESKTOP:~/github/NoCheatZ-4/scripts# python version.py
#include "version.h"

char const * const NCZ_VERSION_GIT = "v4-r54-0-gf94570c";
char const * const NCZ_VERSION_GIT_SHORT = "v4-r54";


Traceback (most recent call last):
  File "version.py", line 19, in <module>
    with open("../server-plugin/Code/version.cpp", "w") as outfile:
IOError: [Errno 5] Input/output error: '../server-plugin/Code/version.cpp'

```

```
root@T1MOXA-DESKTOP:~/github/NoCheatZ-4/server-plugin# make release CXX=g++-4.8
make[1]: Entering directory '/root/github/NoCheatZ-4/server-plugin'
mkdir -p ../Builds/Release/addons/NoCheatZ/
mkdir -p ../Builds/Release/cfg/
mkdir -p ../Builds/Release/logs/NoCheatZ_4_Logs/
mkdir -p ../Builds/Release/NoCheatZ-autorecords
cp ./Res/nocheatz.vdf ../Builds/Release/addons/
cp ./Res/config.ini ../Builds/Release/addons/NoCheatZ/
cp ./Res/nocheatz.cfg ../Builds/Release/cfg/nocheatz.cfg ;true
cat ./Code/version.cpp
cat: ./Code/version.cpp: No such file or directory
Makefile:180: recipe for target 'prepare-build' failed
make[1]: *** [prepare-build] Error 1
make[1]: Leaving directory '/root/github/NoCheatZ-4/server-plugin'
Makefile:144: recipe for target 'release' failed
make: *** [release] Error 2
```

**Comment by T1MOXA** [comment]
WTF
![image](https://user-images.githubusercontent.com/19938629/28747007-2d7f18a8-749e-11e7-8e94-3f4ee22719f7.png)

**Comment by T1MOXA** [comment]
root@T1MOXA-DESKTOP:~/github/NoCheatZ-4/server-plugin# cd Code
root@T1MOXA-DESKTOP:~/github/NoCheatZ-4/server-plugin/Code# cat version.cpp
cat: version.cpp: No such file or directory

**Comment by T1MOXA** [comment]
I don't know why, but after I deleted this file and created it again with the script - it worked.

**Comment by T1MOXA** [comment]
New error:
```
root@T1MOXA-DESKTOP:~/github/NoCheatZ-4/server-plugin# make release CXX=g++-4.8
make[1]: Entering directory '/root/github/NoCheatZ-4/server-plugin'
mkdir -p ../Builds/Release/addons/NoCheatZ/
mkdir -p ../Builds/Release/cfg/
mkdir -p ../Builds/Release/logs/NoCheatZ_4_Logs/
mkdir -p ../Builds/Release/NoCheatZ-autorecords
cp ./Res/nocheatz.vdf ../Builds/Release/addons/
cp ./Res/config.ini ../Builds/Release/addons/NoCheatZ/
cp ./Res/nocheatz.cfg ../Builds/Release/cfg/nocheatz.cfg ;true
cat ./Code/version.cpp
#include "version.h"

char const * const NCZ_VERSION_GIT = "v4-r54-0-gf94570c";
char const * const NCZ_VERSION_GIT_SHORT = "v4-r54";

Building unit-tests
gtest-all.o
HeapMemoryManager.o
unit-tests.o
unit-tests.so
Using built-in specs.
COLLECT_GCC=g++-4.8
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.5-4ubuntu2' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.5 (Ubuntu 4.8.5-4ubuntu2)
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/4.8/:/usr/lib/gcc/x86_64-linux-gnu/4.8/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/4.8/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/4.8/32/:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib32/:/lib/../lib32/:/usr/lib/../lib32/:/usr/lib/gcc/x86_64-linux-gnu/4.8/:/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-std=c++11' '-mtune=i486' '-march=x86-64' '-mmmx' '-v' '-static-libgcc' '-m32' '-o' './unit-tests/unit-tests'
 /usr/lib/gcc/x86_64-linux-gnu/4.8/collect2 --sysroot=/ --build-id --eh-frame-hdr -m elf_i386 --hash-style=gnu --as-needed -dynamic-linker /lib/ld-linux.so.2 -z relro -o ./unit-tests/unit-tests /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib32/crt1.o /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib32/crti.o /usr/lib/gcc/x86_64-linux-gnu/4.8/32/crtbegin.o -L/usr/lib/gcc/x86_64-linux-gnu/4.8/32 -L/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib32 -L/lib/../lib32 -L/usr/lib/../lib32 -L/usr/lib/gcc/x86_64-linux-gnu/4.8 -L/usr/lib/gcc/x86_64-linux-gnu/4.8/../../.. ./unit-tests/Release/unit-tests.o ./unit-tests/Release/HeapMemoryManager.o ./unit-tests/Release/gtest-all.o --as-needed --no-undefined -ldl -lpthread -lstdc++ -lm -lgcc -lgcc_eh -lc -lgcc -lgcc_eh /usr/lib/gcc/x86_64-linux-gnu/4.8/32/crtend.o /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib32/crtn.o
Starting unit-tests
/bin/bash: ./unit-tests/unit-tests: cannot execute binary file: Exec format error
Makefile:163: recipe for target 'unit-tests' failed
make[1]: *** [unit-tests] Error 126
make[1]: Leaving directory '/root/github/NoCheatZ-4/server-plugin'
Makefile:144: recipe for target 'release' failed
make: *** [release] Error 2
```

**Comment by T1MOXA** [comment]
Cheers. All right now, thank you.

**Comment by T1MOXA** [comment]
You can update instructions for compiling ?
