### ISSUE TITLE
crash at start

### ISSUE THREAD

**Issue by askovpen** [L-EARN/NoCheatZ-4#55]
```
[New Thread 0xede64b40 (LWP 2604)]
[New Thread 0xed663b40 (LWP 2605)]
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
Game engine asking for ISERVERPLUGINCALLBACKS003

Program received signal SIGSEGV, Segmentation fault.
0xec616c6b in HeapMemoryManager::AllocateMemory (bytes=28, new_capacity=@0x0: <error reading variable>, align_of=16)
    at Code/Misc/HeapMemoryManager.cpp:79
79                      new_capacity = align_of;
(gdb) bt
#0  0xec616c6b in HeapMemoryManager::AllocateMemory (bytes=28, new_capacity=@0x0: <error reading variable>, align_of=16)
    at Code/Misc/HeapMemoryManager.cpp:79
#1  0xec60cf5d in Singleton<CNoCheatZPlugin>::CreateInstance () at Code/Misc/temp_singleton.h:49
#2  0xec60a633 in __CreatePlugin_interface () at Code/plugin.cpp:48
#3  0xec60a687 in CreateInterfaceInternal (pName=0xf6c805c1 "ISERVERPLUGINCALLBACKS003", pReturnCode=0x0)
    at Code/plugin.cpp:57
#4  0xec60a6a5 in SourceSdk::CreateInterface (pName=0xf6c805c1 "ISERVERPLUGINCALLBACKS003", pReturnCode=0x0)
    at Code/plugin.cpp:62
#5  0xf69b836b in CPlugin::Load(char const*) () from /mnt/p/home/steam/csgo/bin/engine.so
#6  0xf69b93a7 in CServerPlugin::LoadPlugin(char const*) () from /mnt/p/home/steam/csgo/bin/engine.so
#7  0xf69b961b in CServerPlugin::LoadPlugins() () from /mnt/p/home/steam/csgo/bin/engine.so
#8  0xf69b1f55 in SV_InitGameDLL() () from /mnt/p/home/steam/csgo/bin/engine.so
#9  0xf692535d in Host_Init(bool) () from /mnt/p/home/steam/csgo/bin/engine.so
#10 0xf69c6cbb in Sys_InitGame(void* (*)(char const*, int*), char const*, void*, int) ()
   from /mnt/p/home/steam/csgo/bin/engine.so
#11 0xf69ca0e8 in CEngine::Load(bool, char const*) () from /mnt/p/home/steam/csgo/bin/engine.so
#12 0xf69c767e in CModAppSystemGroup::Main() () from /mnt/p/home/steam/csgo/bin/engine.so
#13 0xf6b17e70 in CAppSystemGroup::Run() () from /mnt/p/home/steam/csgo/bin/engine.so
#14 0xf69c88b7 in CDedicatedServerAPI::ModInit(ModInfo_t&) () from /mnt/p/home/steam/csgo/bin/engine.so
#15 0xf784cd94 in CDedicatedAppSystemGroup::Main() () from ./bin/dedicated.so
#16 0xf7870740 in CAppSystemGroup::Run() () from ./bin/dedicated.so
#17 0xf787196e in CSteamApplication::Main() () from ./bin/dedicated.so
#18 0xf7870740 in CAppSystemGroup::Run() () from ./bin/dedicated.so
#19 0xf7812d73 in main () from ./bin/dedicated.so
#20 0x080486f9 in main ()
```

**Comment by askovpen** [comment]
```
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
Game engine asking for ISERVERPLUGINCALLBACKS003
CNoCheatZPlugin interface created with CSGO callbacks ...
[NoCheatZ v4-beta-r1-140-gddcf05f-dirty-debug] Loading ...
Detected game CSGO
[NoCheatZ v4-beta-r1-140-gddcf05f-dirty-debug] ConfigManager : Disabled system validationtester
[NoCheatZ v4-beta-r1-140-gddcf05f-dirty-debug] ConfigManager : Disabled system radarhackblocker
[NoCheatZ v4-beta-r1-140-gddcf05f-dirty-debug] ConfigManager : Disabled system badusercmdblocker
*** Error in `/mnt/p/home/steam/csgo/srcds_linux': corrupted double-linked list: 0x08fcebc0 ***
warning: Corrupted shared library list: 0xf2417b40 != 0x72

Program received signal SIGSEGV, Segmentation fault.
0xf7fed056 in ?? () from /lib/ld-linux.so.2
(gdb) bt
#0  0xf7fed056 in ?? () from /lib/ld-linux.so.2
#1  0xf7fe8d35 in ?? () from /lib/ld-linux.so.2
#2  0xf7fec939 in ?? () from /lib/ld-linux.so.2
#3  0xf7eb3fee in ?? () from /lib32/libc.so.6
#4  0xf7fe8d35 in ?? () from /lib/ld-linux.so.2
#5  0xf7eb40b7 in ?? () from /lib32/libc.so.6
#6  0xf7eb413e in __libc_dlopen_mode () from /lib32/libc.so.6
#7  0xf7e90483 in ?? () from /lib32/libc.so.6
#8  0xf7f57e59 in __pthread_once_slow () from /lib32/libpthread.so.0
#9  0xf7e90703 in backtrace () from /lib32/libc.so.6
#10 0xf7db2679 in ?? () from /lib32/libc.so.6
#11 0xf7e036ab in ?? () from /lib32/libc.so.6
#12 0xf7e0984f in ?? () from /lib32/libc.so.6
#13 0xf7e0bd32 in ?? () from /lib32/libc.so.6
#14 0xf7e0cec0 in malloc () from /lib32/libc.so.6
#15 0xf7e0ee9c in posix_memalign () from /lib32/libc.so.6
#16 0xec636642 in ?? ()
#17 0xec6367d3 in ?? ()
#18 0xec62fad6 in ?? ()
#19 0xec62f6f5 in ?? ()
#20 0xec62ee75 in ?? ()
#21 0xec62effc in ?? ()
#22 0xec62cb0a in ?? ()
#23 0xec62f06e in ?? ()
#24 0xec6478b5 in ?? ()
#25 0xec6455a6 in ?? ()
#26 0xec653cfe in ?? ()
#27 0xec62aba3 in ?? ()
#28 0xf69b83a6 in CPlugin::Load(char const*) () from /mnt/p/home/steam/csgo/bin/engine.so
#29 0xf69b93a7 in CServerPlugin::LoadPlugin(char const*) () from /mnt/p/home/steam/csgo/bin/engine.so
#30 0xf69b961b in CServerPlugin::LoadPlugins() () from /mnt/p/home/steam/csgo/bin/engine.so
#31 0xf69b1f55 in SV_InitGameDLL() () from /mnt/p/home/steam/csgo/bin/engine.so
#32 0xf692535d in Host_Init(bool) () from /mnt/p/home/steam/csgo/bin/engine.so
#33 0xf69c6cbb in Sys_InitGame(void* (*)(char const*, int*), char const*, void*, int) ()
   from /mnt/p/home/steam/csgo/bin/engine.so
#34 0xf69ca0e8 in CEngine::Load(bool, char const*) () from /mnt/p/home/steam/csgo/bin/engine.so
#35 0xf69c767e in CModAppSystemGroup::Main() () from /mnt/p/home/steam/csgo/bin/engine.so
#36 0xf6b17e70 in CAppSystemGroup::Run() () from /mnt/p/home/steam/csgo/bin/engine.so
#37 0xf69c88b7 in CDedicatedServerAPI::ModInit(ModInfo_t&) () from /mnt/p/home/steam/csgo/bin/engine.so
---Type <return> to continue, or q <return> to quit--- 
#38 0xf784cd94 in CDedicatedAppSystemGroup::Main() () from ./bin/dedicated.so
#39 0xf7870740 in CAppSystemGroup::Run() () from ./bin/dedicated.so
#40 0xf787196e in CSteamApplication::Main() () from ./bin/dedicated.so
#41 0xf7870740 in CAppSystemGroup::Run() () from ./bin/dedicated.so
#42 0xf7812d73 in main () from ./bin/dedicated.so
#43 0x080486f9 in main ()

**Comment by L-EARN** [comment]
I will look into this today.

**Comment by askovpen** [comment]
```
(gdb) bt full
#0  0xf7e2f16d in wcsnlen () from /lib32/libc.so.6
No symbol table info available.
#1  0xf7e2e95c in wcsrtombs () from /lib32/libc.so.6
No symbol table info available.
#2  0xf7dc9d96 in wcstombs () from /lib32/libc.so.6
No symbol table info available.
#3  0xec654682 in String<char>::ConvertToChar (in=..., out=...) at ../server-plugin/Code/Misc/temp_basicstring.h:518
        __PRETTY_FUNCTION__ = "static void String<pod>::ConvertToChar(const String<wchar_t>&, String<char>&) [with pod = char]"
        cpsize = 0
#4  0xec653e78 in String<char>::lower (this=0xffff9f20) at ../server-plugin/Code/Misc/temp_basicstring.h:487
        t = {<HeapMemoryManager::OverrideNew<16u>> = {m_hmm_capacity = 0}, static npos = <optimized out>, 
          m_alloc = 0x0, m_size = 0, m_capacity = 0}
#5  0xec65809c in GetIniAttributeValue (file=..., root=..., attrib=..., value=...) at Code/Systems/ConfigManager.cpp:60
        attrib_expect = {<HeapMemoryManager::OverrideNew<16u>> = {m_hmm_capacity = 0}, static npos = <optimized out>, 
          m_alloc = 0x8fce078 "b", m_size = 17, m_capacity = 64}
        root_expect = {<HeapMemoryManager::OverrideNew<16u>> = {m_hmm_capacity = 0}, static npos = <optimized out>, 
          m_alloc = 0x8fce0e0 "[csgo]", m_size = 6, m_capacity = 64}
        buf_ref = {<HeapMemoryManager::OverrideNew<16u>> = {m_hmm_capacity = 0}, static npos = <optimized out>, 
          m_alloc = 0x8fce4e8 "", m_size = 0, m_capacity = 128}
        buf = "\000isable_systems=BadUserCmdBlocker\000adarHackBlocker;BadUserCmdBlocker\000\020\366\204\354\000\000\000\000Ԇc\354\000\000\000\000\b\000\000\000\001\000\000\000ȟ\377\377\354\206c\354\370\365\204\354\000\366\204\354\376\205\334\367\000`\364\367\004\000\000\000\004\000\000\000\004\000\000\000\247\207\334\367\340\365\204\354\020\330\000\t \000\000\000\247\207\334\367\000\366\204\354\000\000\000\000Ԇc\354\000\000\000\000\b\000\000\000\000\000\000\000\030\240\377\377\354\206c\354\330\365\204\354\340\365\204\354\376\205\334\367\000`\364\367\b\000\000\000\b\000\000\000"...
        root_found = true
        __PRETTY_FUNCTION__ = "bool GetIniAttributeValue(std::ifstream&, const basic_string&, const basic_string&, basic_string&)"
#6  0xec6587b5 in ConfigManager::LoadConfig (this=0x8fc9100) at Code/Systems/ConfigManager.cpp:136
        systems = {m_Memory = {static INVALID_INDEX = <optimized out>, m_pMemory = 0x0, m_nAllocationCount = 150790808, 
            m_nGrowSize = 16}, m_Size = 64, m_pElements = 0x0}
        value = {<HeapMemoryManager::OverrideNew<16u>> = {m_hmm_capacity = 0}, static npos = <optimized out>, 
          m_alloc = 0x8fce3b0 "282", m_size = 3, m_capacity = 64}
        path = {<HeapMemoryManager::OverrideNew<16u>> = {m_hmm_capacity = 0}, static npos = <optimized out>, 
          m_alloc = 0x8fcdf88 "csgo/addons/NoCheatZ/config.ini", m_size = 31, m_capacity = 64}
        gamename = {<HeapMemoryManager::OverrideNew<16u>> = {m_hmm_capacity = 0}, static npos = <optimized out>, 
          m_alloc = 0x8fcd2f8 "csgo", m_size = 4, m_capacity = 512}
        file = {<std::basic_istream<char, std::char_traits<char> >> = {<std::basic_ios<char, std::char_traits<char> >> = {<std::ios_base> = {_vptr.ios_base = 0xf77b9bc0 <vtable for std::basic_ifstream<char, std::char_traits<char> >+32>, 
---Type <return> to continue, or q <return> to quit---
                static boolalpha = std::_S_boolalpha, static dec = std::_S_dec, static fixed = std::_S_fixed, 
                static hex = std::_S_hex, static internal = std::_S_internal, static left = std::_S_left, 
                static oct = std::_S_oct, static right = std::_S_right, static scientific = std::_S_scientific, 
                static showbase = std::_S_showbase, static showpoint = std::_S_showpoint, 
                static showpos = std::_S_showpos, static skipws = std::_S_skipws, static unitbuf = std::_S_unitbuf, 
                static uppercase = std::_S_uppercase, static adjustfield = std::_S_adjustfield, 
                static basefield = std::_S_basefield, static floatfield = std::_S_floatfield, 
                static badbit = std::_S_badbit, static eofbit = std::_S_eofbit, static failbit = std::_S_failbit, 
                static goodbit = std::_S_goodbit, static app = std::_S_app, static ate = std::_S_ate, 
                static binary = std::_S_bin, static in = std::_S_in, static out = std::_S_out, 
                static trunc = std::_S_trunc, static beg = std::_S_beg, static cur = std::_S_cur, 
                static end = std::_S_end, _M_precision = 6, _M_width = 0, _M_flags = 4098, 
                _M_exception = std::_S_goodbit, _M_streambuf_state = (std::_S_eofbit | std::_S_failbit), 
                _M_callbacks = 0x0, _M_word_zero = {_M_pword = 0x0, _M_iword = 0}, _M_local_word = {{_M_pword = 0x0, 
                    _M_iword = 0}, {_M_pword = 0x0, _M_iword = 0}, {_M_pword = 0x0, _M_iword = 0}, {_M_pword = 0x0, 
                    _M_iword = 0}, {_M_pword = 0x0, _M_iword = 0}, {_M_pword = 0x0, _M_iword = 0}, {_M_pword = 0x0, 
                    _M_iword = 0}, {_M_pword = 0x0, _M_iword = 0}}, _M_word_size = 8, _M_word = 0xffffa4a8, 
                _M_ios_locale = {static none = 0, static ctype = 1, static numeric = 2, static collate = 4, 
                  static time = 8, static monetary = 16, static messages = 32, static all = 63, 
                  _M_impl = 0xf77bdd64 <(anonymous namespace)::c_locale_impl>, static _S_classic = 
    0xf77bdd64 <(anonymous namespace)::c_locale_impl>, 
                  static _S_global = 0xf77bdd64 <(anonymous namespace)::c_locale_impl>, static _S_categories = 
    0xf77b8b38 <__gnu_cxx::category_names>, static _S_once = 2}}, _M_tie = 0x0, _M_fill = 0 '\000', 
              _M_fill_init = false, _M_streambuf = 0xffffa3fc, _M_ctype = 0xf77bdea0 <(anonymous namespace)::ctype_c>, 
              _M_num_put = 0xf77be148 <(anonymous namespace)::num_put_c>, 
              _M_num_get = 0xf77be140 <(anonymous namespace)::num_get_c>}, 
            _vptr.basic_istream = 0xf77b9bac <vtable for std::basic_ifstream<char, std::char_traits<char> >+12>, 
            _M_gcount = 0}, _M_filebuf = {<std::basic_streambuf<char, std::char_traits<char> >> = {
              _vptr.basic_streambuf = 0xf77b9b30 <vtable for std::basic_filebuf<char, std::char_traits<char> >+8>, 
              _M_in_beg = 0x900b808 "[CONFIG]\nconfig_version=1\n[CSGO]\ngetdatadescmap_windows=11\ngetdatadescmap_linux=12\nsettransmit_windows=22\nsettransmit_linux=23\nmhgroundentity_windows=175\nmhgroundentity_linux=177\nweaponequip_windows=2"..., 
              _M_in_cur = 0x900b808 "[CONFIG]\nconfig_version=1\n[CSGO]\ngetdatadescmap_windows=11\ngetdatadescmap_linux=12\nsettransmit_windows=22\nsettransmit_linux=23\nmhgroundentity_windows=175\nmhgroundentity_linux=177\nweaponequip_windows=2"..., 
              _M_in_end = 0x900b808 "[CONFIG]\nconfig_version=1\n[CSGO]\ngetdatadescmap_windows=11\ngetdatadescmap_linux=12\nsettransmit_windows=22\nsettransmit_linux=23\nmhgroundentity_windows=175\nmhgroundentity_linux=177\nweaponequip_windows=2"..., _M_out_beg = 0x0, _M_out_cur = 0x0, _M_out_end = 0x0, _M_buf_locale = {static none = 0, static ctype = 1, 
                static numeric = 2, static collate = 4, static time = 8, static monetary = 16, static messages = 32, 
---Type <return> to continue, or q <return> to quit---
                static all = 63, _M_impl = 0xf77bdd64 <(anonymous namespace)::c_locale_impl>, 
                static _S_classic = 0xf77bdd64 <(anonymous namespace)::c_locale_impl>, 
                static _S_global = 0xf77bdd64 <(anonymous namespace)::c_locale_impl>, 
                static _S_categories = 0xf77b8b38 <__gnu_cxx::category_names>, static _S_once = 2}}, _M_lock = {
              __data = {__lock = 0, __count = 0, __owner = 0, __kind = 0, __nusers = 0, {__spins = 0, __list = {
                    __next = 0x0}}}, __size = '\000' <repeats 23 times>, __align = 0}, _M_file = {_M_cfile = 0x8fc87b0, 
              _M_cfile_created = true}, _M_mode = std::_S_in, _M_state_beg = {__count = 0, __value = {__wch = 0, 
                __wchb = "\000\000\000"}}, _M_state_cur = {__count = 0, __value = {__wch = 0, 
                __wchb = "\000\000\000"}}, _M_state_last = {__count = 0, __value = {__wch = 0, 
                __wchb = "\000\000\000"}}, 
            _M_buf = 0x900b808 "[CONFIG]\nconfig_version=1\n[CSGO]\ngetdatadescmap_windows=11\ngetdatadescmap_linux=12\nsettransmit_windows=22\nsettransmit_linux=23\nmhgroundentity_windows=175\nmhgroundentity_linux=177\nweaponequip_windows=2"..., _M_buf_size = 8192, _M_buf_allocated = true, _M_reading = false, _M_writing = false, _M_pback = 0 '\000', 
            _M_pback_cur_save = 0x0, _M_pback_end_save = 0x0, _M_pback_init = false, _M_codecvt = 
    0xf77be0c0 <(anonymous namespace)::codecvt_c>, _M_ext_buf = 0x0, _M_ext_buf_size = 0, _M_ext_next = 0x0, 
            _M_ext_end = 0x0}}
#7  0xec62ca31 in CNoCheatZPlugin::Load (this=0x8fcbad0, 
    _interfaceFactory=0xf6b16d40 <AppSystemCreateInterfaceFn(char const*, int*)>, 
    gameServerFactory=0xf3aa42f0 <CreateInterface>) at Code/plugin.cpp:189
        pinstance = 0x0
        __PRETTY_FUNCTION__ = "virtual bool CNoCheatZPlugin::Load(SourceSdk::CreateInterfaceFn, SourceSdk::CreateInterfaceFn)"
#8  0xf69b83a6 in CPlugin::Load(char const*) () from /mnt/p/home/steam/csgo/bin/engine.so
No symbol table info available.
#9  0xf69b93a7 in CServerPlugin::LoadPlugin(char const*) () from /mnt/p/home/steam/csgo/bin/engine.so
No symbol table info available.
#10 0xf69b961b in CServerPlugin::LoadPlugins() () from /mnt/p/home/steam/csgo/bin/engine.so
No symbol table info available.
#11 0xf69b1f55 in SV_InitGameDLL() () from /mnt/p/home/steam/csgo/bin/engine.so
No symbol table info available.
#12 0xf692535d in Host_Init(bool) () from /mnt/p/home/steam/csgo/bin/engine.so
No symbol table info available.
#13 0xf69c6cbb in Sys_InitGame(void* (*)(char const*, int*), char const*, void*, int) ()
   from /mnt/p/home/steam/csgo/bin/engine.so
No symbol table info available.
#14 0xf69ca0e8 in CEngine::Load(bool, char const*) () from /mnt/p/home/steam/csgo/bin/engine.so
No symbol table info available.
#15 0xf69c767e in CModAppSystemGroup::Main() () from /mnt/p/home/steam/csgo/bin/engine.so
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#16 0xf6b17e70 in CAppSystemGroup::Run() () from /mnt/p/home/steam/csgo/bin/engine.so
No symbol table info available.
#17 0xf69c88b7 in CDedicatedServerAPI::ModInit(ModInfo_t&) () from /mnt/p/home/steam/csgo/bin/engine.so
No symbol table info available.
#18 0xf784cd94 in CDedicatedAppSystemGroup::Main() () from ./bin/dedicated.so
No symbol table info available.
#19 0xf7870740 in CAppSystemGroup::Run() () from ./bin/dedicated.so
No symbol table info available.
#20 0xf787196e in CSteamApplication::Main() () from ./bin/dedicated.so
No symbol table info available.
#21 0xf7870740 in CAppSystemGroup::Run() () from ./bin/dedicated.so
No symbol table info available.
#22 0xf7812d73 in main () from ./bin/dedicated.so
No symbol table info available.
#23 0x080486f9 in main ()
No symbol table info available.
```

**Comment by askovpen** [comment]
not fixed
```
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
Game engine asking for ISERVERPLUGINCALLBACKS003
CNoCheatZPlugin interface created with CSGO callbacks ...
[NoCheatZ v4-beta-r1-156-gc9968c1-dirty-debug] Loading ...
Detected game CSGO
[Thread 0xede64b40 (LWP 29326) exited]

Program received signal SIGSEGV, Segmentation fault.
0xf7e2f16d in wcsnlen () from /lib32/libc.so.6
(gdb) bt
#0  0xf7e2f16d in wcsnlen () from /lib32/libc.so.6
#1  0xf7e2e95c in wcsrtombs () from /lib32/libc.so.6
#2  0xf7dc9d96 in wcstombs () from /lib32/libc.so.6
#3  0xec65318a in String<char>::ConvertToChar (in=..., out=...) at ../server-plugin/Code/Misc/temp_basicstring.h:518
#4  0xec652980 in String<char>::lower (this=0xffff9f20) at ../server-plugin/Code/Misc/temp_basicstring.h:487
#5  0xec656b92 in GetIniAttributeValue (file=..., root=..., attrib=..., value=...) at Code/Systems/ConfigManager.cpp:60
#6  0xec6572ab in ConfigManager::LoadConfig (this=0x8fc9120) at Code/Systems/ConfigManager.cpp:136
#7  0xec628c89 in CNoCheatZPlugin::Load (this=0x8fcbaf0, 
    _interfaceFactory=0xf6b16d40 <AppSystemCreateInterfaceFn(char const*, int*)>, 
    gameServerFactory=0xf3aa42f0 <CreateInterface>) at Code/plugin.cpp:185
#8  0xf69b83a6 in CPlugin::Load(char const*) () from /mnt/p/home/steam/csgo/bin/engine.so
#9  0xf69b93a7 in CServerPlugin::LoadPlugin(char const*) () from /mnt/p/home/steam/csgo/bin/engine.so
#10 0xf69b961b in CServerPlugin::LoadPlugins() () from /mnt/p/home/steam/csgo/bin/engine.so
#11 0xf69b1f55 in SV_InitGameDLL() () from /mnt/p/home/steam/csgo/bin/engine.so
#12 0xf692535d in Host_Init(bool) () from /mnt/p/home/steam/csgo/bin/engine.so
#13 0xf69c6cbb in Sys_InitGame(void* (*)(char const*, int*), char const*, void*, int) ()
   from /mnt/p/home/steam/csgo/bin/engine.so
#14 0xf69ca0e8 in CEngine::Load(bool, char const*) () from /mnt/p/home/steam/csgo/bin/engine.so
#15 0xf69c767e in CModAppSystemGroup::Main() () from /mnt/p/home/steam/csgo/bin/engine.so
#16 0xf6b17e70 in CAppSystemGroup::Run() () from /mnt/p/home/steam/csgo/bin/engine.so
#17 0xf69c88b7 in CDedicatedServerAPI::ModInit(ModInfo_t&) () from /mnt/p/home/steam/csgo/bin/engine.so
#18 0xf784cd94 in CDedicatedAppSystemGroup::Main() () from ./bin/dedicated.so
#19 0xf7870740 in CAppSystemGroup::Run() () from ./bin/dedicated.so
#20 0xf787196e in CSteamApplication::Main() () from ./bin/dedicated.so
#21 0xf7870740 in CAppSystemGroup::Run() () from ./bin/dedicated.so
#22 0xf7812d73 in main () from ./bin/dedicated.so
#23 0x080486f9 in main ()
```

**Comment by askovpen** [comment]
sorry. fixed. bad makefile. if changed header file - not recompile depencies.

**Comment by askovpen** [comment]
http://stackoverflow.com/questions/2394609/makefile-header-dependencies

**Comment by L-EARN** [comment]
That could be a great idea, but I don't really understand how this works.
So when I see sources are not compiled, I just clean and rebuild you know ...

I will try to implement this.
