### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by askovpen** [L-EARN/NoCheatZ-4#59]
```
Game will not start until both teams have players.
Dropped Пуштун from server: Disconnect
-> Reservation cookie 0:  reason reserved(yes), clients(no), reservationexpires(0.00)
Server is hibernating
[NoCheatZ v4-beta-r1-156-gc9968c1-dirty-debug] DEBUG : CNoCheatZPlugin::ClientDisconnect
Game will not start until both teams have players.
Completed GOTV demo "NoCheatZ-autorecords/de_dust2-07-04-16_23-19-36.dem", recording time 21.7
MasterRequestRestart
Your server is out of date and will be shutdown during hibernation or changelevel, whichever comes first.
Host state 5 at Tue Jul  5 06:54:56 2016
 -- sv_shutdown hibernating server right now.
[NoCheatZ v4-beta-r1-156-gc9968c1-dirty-debug] DEBUG : CNoCheatZPlugin::LevelShutdown
[NoCheatZ v4-beta-r1-156-gc9968c1-dirty-debug] 56805.9 : Stoping AutoTVRecord
GOTV[0] not active.
[NoCheatZ v4-beta-r1-156-gc9968c1-dirty-debug] TV record ended in NoCheatZ-autorecords/de_dust2-07-04-16_23-19-36.dem with 682 ticks (10.656250 seconds)
[NoCheatZ v4-beta-r1-156-gc9968c1-dirty-debug] 56806 : Stoping SpamConnectTester
[Thread 0xe63ffb40 (LWP 19049) exited]
[Thread 0xe6dffb40 (LWP 17989) exited]
[Thread 0xeb5f3b40 (LWP 19052) exited]
[Thread 0xe7011b40 (LWP 17983) exited]
[Thread 0xe66ffb40 (LWP 17991) exited]
[Thread 0xe6affb40 (LWP 17985) exited]
[NoCheatZ v4-beta-r1-156-gc9968c1-dirty-debug] DEBUG : VirtualTableHook : function 0xEC7F0FE6 at 0xF35C57A4 replaced by 0xEE1E7E50.
[NoCheatZ v4-beta-r1-156-gc9968c1-dirty-debug] DEBUG : VirtualTableHook : function 0xEC7F0FE6 at 0xF6C8D424 replaced by 0xEE1E7E50.
[NoCheatZ v4-beta-r1-156-gc9968c1-dirty-debug] DEBUG : VirtualTableHook : function 0xEC7EFF8C at 0xF350D49C replaced by 0xEC3A4CF0.
srcds_linux: ../server-plugin/Code/Misc/temp_singleton.h:82: static C* const Singleton<C>::GetInstance() [with C = HookGuard<PlayerRunCommandHookListener>]: Assertion `hClass::instance' failed.

Program received signal SIGABRT, Aborted.
0xf7fda9f2 in ?? () from /lib/ld-linux.so.2
(gdb) bt
#0  0xf7fda9f2 in ?? () from /lib/ld-linux.so.2
#1  0xf7dc6977 in raise () from /lib32/libc.so.6
#2  0xf7dc7f49 in abort () from /lib32/libc.so.6
#3  0xf7dbfa27 in ?? () from /lib32/libc.so.6
#4  0xf7dbfaab in __assert_fail () from /lib32/libc.so.6
#5  0xec7f0544 in Singleton<HookGuard<PlayerRunCommandHookListener> >::GetInstance ()
    at ../server-plugin/Code/Misc/temp_singleton.h:82
#6  0xec7efe18 in PlayerRunCommandHookListener::~PlayerRunCommandHookListener (this=0x8fda558, 
    __in_chrg=<optimized out>) at Code/Hooks/PlayerRunCommandHookListener.cpp:45
#7  0xec809b70 in ShotTester::~ShotTester (this=0x8fd8e80, __in_chrg=<optimized out>)
    at Code/Systems/Testers/ShotTester.cpp:36
#8  0xec7ebfb8 in Singleton<ShotTester>::DestroyInstance () at Code/Misc/temp_singleton.h:66
#9  0xec7e8999 in CNoCheatZPlugin::DestroySingletons () at Code/plugin.cpp:106
#10 0xec7e90e2 in CNoCheatZPlugin::Unload (this=0x8fcbaf0) at Code/plugin.cpp:286
#11 0xf69b81ac in CPlugin::Unload() () from /mnt/p/home/steam/csgo/bin/engine.so
#12 0xf69b92b9 in CServerPlugin::UnloadPlugins() () from /mnt/p/home/steam/csgo/bin/engine.so
#13 0xf69af307 in SV_ShutdownGameDLL() () from /mnt/p/home/steam/csgo/bin/engine.so
#14 0xf69c76f2 in CModAppSystemGroup::Main() () from /mnt/p/home/steam/csgo/bin/engine.so
#15 0xf6b17e70 in CAppSystemGroup::Run() () from /mnt/p/home/steam/csgo/bin/engine.so
#16 0xf69c88b7 in CDedicatedServerAPI::ModInit(ModInfo_t&) () from /mnt/p/home/steam/csgo/bin/engine.so
#17 0xf784cd94 in CDedicatedAppSystemGroup::Main() () from ./bin/dedicated.so
#18 0xf7870740 in CAppSystemGroup::Run() () from ./bin/dedicated.so
#19 0xf787196e in CSteamApplication::Main() () from ./bin/dedicated.so
#20 0xf7870740 in CAppSystemGroup::Run() () from ./bin/dedicated.so
#21 0xf7812d73 in main () from ./bin/dedicated.so
#22 0x080486f9 in main ()

**Comment by askovpen** [comment]
startup error


```
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
Game engine asking for ISERVERPLUGINCALLBACKS003
srcds_linux: Code/Misc/temp_singleton.h:54: static void Singleton<C>::CreateInstance() [with C = CNoCheatZPlugin]: Assertion `IsCreated ()' failed.

Program received signal SIGABRT, Aborted.
0xf7fda9f2 in ?? () from /lib/ld-linux.so.2
(gdb) bt
#0  0xf7fda9f2 in ?? () from /lib/ld-linux.so.2
#1  0xf7dc6977 in raise () from /lib32/libc.so.6
#2  0xf7dc7f49 in abort () from /lib32/libc.so.6
#3  0xf7dbfa27 in ?? () from /lib32/libc.so.6
#4  0xf7dbfaab in __assert_fail () from /lib32/libc.so.6
#5  0xec7e60a8 in Singleton<CNoCheatZPlugin>::CreateInstance () at Code/Misc/temp_singleton.h:54
#6  0xec7e3848 in __CreatePlugin_interface () at Code/plugin.cpp:49
#7  0xec7e389c in CreateInterfaceInternal (pName=0xf6c805c1 "ISERVERPLUGINCALLBACKS003", pReturnCode=0x0)
    at Code/plugin.cpp:58
#8  0xec7e38ba in SourceSdk::CreateInterface (pName=0xf6c805c1 "ISERVERPLUGINCALLBACKS003", pReturnCode=0x0)
    at Code/plugin.cpp:63
#9  0xf69b836b in CPlugin::Load(char const*) () from /mnt/p/home/steam/csgo/bin/engine.so
#10 0xf69b93a7 in CServerPlugin::LoadPlugin(char const*) () from /mnt/p/home/steam/csgo/bin/engine.so
#11 0xf69b961b in CServerPlugin::LoadPlugins() () from /mnt/p/home/steam/csgo/bin/engine.so
#12 0xf69b1f55 in SV_InitGameDLL() () from /mnt/p/home/steam/csgo/bin/engine.so
#13 0xf692535d in Host_Init(bool) () from /mnt/p/home/steam/csgo/bin/engine.so
#14 0xf69c6cbb in Sys_InitGame(void* (*)(char const*, int*), char const*, void*, int) ()
   from /mnt/p/home/steam/csgo/bin/engine.so
#15 0xf69ca0e8 in CEngine::Load(bool, char const*) () from /mnt/p/home/steam/csgo/bin/engine.so
#16 0xf69c767e in CModAppSystemGroup::Main() () from /mnt/p/home/steam/csgo/bin/engine.so
#17 0xf6b17e70 in CAppSystemGroup::Run() () from /mnt/p/home/steam/csgo/bin/engine.so
#18 0xf69c88b7 in CDedicatedServerAPI::ModInit(ModInfo_t&) () from /mnt/p/home/steam/csgo/bin/engine.so
#19 0xf784cd94 in CDedicatedAppSystemGroup::Main() () from ./bin/dedicated.so
#20 0xf7870740 in CAppSystemGroup::Run() () from ./bin/dedicated.so
#21 0xf787196e in CSteamApplication::Main() () from ./bin/dedicated.so
#22 0xf7870740 in CAppSystemGroup::Run() () from ./bin/dedicated.so
#23 0xf7812d73 in main () from ./bin/dedicated.so
#24 0x080486f9 in main ()

**Comment by askovpen** [comment]
```
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
Game engine asking for ISERVERPLUGINCALLBACKS003
CNoCheatZPlugin interface created with CSGO callbacks ...
[NoCheatZ v4-beta-r1-173-g71dcd9e-debug] Loading ...
Detected game CSGO
[NoCheatZ v4-beta-r1-173-g71dcd9e-debug] ConfigManager : Disabled system validationtester
[NoCheatZ v4-beta-r1-173-g71dcd9e-debug] ConfigManager : Disabled system radarhackblocker
[NoCheatZ v4-beta-r1-173-g71dcd9e-debug] ConfigManager : Disabled system badusercmdblocker
[NoCheatZ v4-beta-r1-173-g71dcd9e-debug] 0.0211952 : Starting AutoTVRecord
[NoCheatZ v4-beta-r1-173-g71dcd9e-debug] DEBUG : VirtualTableHook : function 0xEDF2AE50 at 0xF6C8D424 replaced by 0xEC7DAE14.
[NoCheatZ v4-beta-r1-173-g71dcd9e-debug] 0.0213371 : Starting SpamConnectTester
srcds_linux: ../server-plugin/Code/Players/NczPlayerManager.h:331: bool PlayerHandler::iterator::operator>(SlotStatus) const: Assertion `IsIteratorValid ()' failed.

Program received signal SIGABRT, Aborted.
0xf7fda9f2 in ?? () from /lib/ld-linux.so.2
(gdb) bt
#0  0xf7fda9f2 in ?? () from /lib/ld-linux.so.2
#1  0xf7dc6977 in raise () from /lib32/libc.so.6
#2  0xf7dc7f49 in abort () from /lib32/libc.so.6
#3  0xf7dbfa27 in ?? () from /lib32/libc.so.6
#4  0xf7dbfaab in __assert_fail () from /lib32/libc.so.6
#5  0xec7da1bb in PlayerHandler::iterator::operator> (this=0xffffa450, other_status=SlotStatus::INVALID)
    at ../server-plugin/Code/Players/NczPlayerManager.h:331
#6  0xec7dae94 in ConCommandHookListener::RT_nDispatch (cmd=0xf6e6d4c0 <exec_command>, args=...)
    at Code/Hooks/ConCommandHookListener.cpp:58
#7  0xf68b5b38 in Cmd_ExecuteCommand(ECommandTarget_t, CCommand const&, cmd_source_t, int) ()
   from /mnt/p/home/steam/csgo/bin/engine.so
#8  0xf68b5d3c in Cbuf_Execute() () from /mnt/p/home/steam/csgo/bin/engine.so
#9  0xec80b373 in SourceSdk::InterfacesProxy::Call_ServerExecute () at SourceSdk/SourceSdk.cpp:2356
#10 0xec7d2564 in CNoCheatZPlugin::Load (this=0x8fcbdc0, 
    _interfaceFactory=0xf6b16d40 <AppSystemCreateInterfaceFn(char const*, int*)>, 
    gameServerFactory=0xf3aa42f0 <CreateInterface>) at Code/plugin.cpp:226
#11 0xf69b83a6 in CPlugin::Load(char const*) () from /mnt/p/home/steam/csgo/bin/engine.so
#12 0xf69b93a7 in CServerPlugin::LoadPlugin(char const*) () from /mnt/p/home/steam/csgo/bin/engine.so
#13 0xf69b961b in CServerPlugin::LoadPlugins() () from /mnt/p/home/steam/csgo/bin/engine.so
#14 0xf69b1f55 in SV_InitGameDLL() () from /mnt/p/home/steam/csgo/bin/engine.so
#15 0xf692535d in Host_Init(bool) () from /mnt/p/home/steam/csgo/bin/engine.so
#16 0xf69c6cbb in Sys_InitGame(void* (*)(char const*, int*), char const*, void*, int) ()
   from /mnt/p/home/steam/csgo/bin/engine.so
#17 0xf69ca0e8 in CEngine::Load(bool, char const*) () from /mnt/p/home/steam/csgo/bin/engine.so
#18 0xf69c767e in CModAppSystemGroup::Main() () from /mnt/p/home/steam/csgo/bin/engine.so
#19 0xf6b17e70 in CAppSystemGroup::Run() () from /mnt/p/home/steam/csgo/bin/engine.so
#20 0xf69c88b7 in CDedicatedServerAPI::ModInit(ModInfo_t&) () from /mnt/p/home/steam/csgo/bin/engine.so
#21 0xf784cd94 in CDedicatedAppSystemGroup::Main() () from ./bin/dedicated.so
#22 0xf7870740 in CAppSystemGroup::Run() () from ./bin/dedicated.so
#23 0xf787196e in CSteamApplication::Main() () from ./bin/dedicated.so
#24 0xf7870740 in CAppSystemGroup::Run() () from ./bin/dedicated.so
#25 0xf7812d73 in main () from ./bin/dedicated.so
#26 0x080486f9 in main ()

**Comment by askovpen** [comment]
```
Initializing Steam libraries for secure Internet server
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[New Thread 0xe7011b40 (LWP 15618)]
[New Thread 0xe6dffb40 (LWP 15619)]
[Thread 0xe6dffb40 (LWP 15619) exited]
[New Thread 0xe6affb40 (LWP 15620)]
[New Thread 0xe69feb40 (LWP 15621)]
[New Thread 0xe66ffb40 (LWP 15622)]
[Thread 0xe69feb40 (LWP 15621) exited]
[Thread 0xe66ffb40 (LWP 15622) exited]
[New Thread 0xe63ffb40 (LWP 15623)]
[Thread 0xe63ffb40 (LWP 15623) exited]
Setting breakpad minidump AppID = 730
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Setting breakpad minidump AppID = 740
Logging into Steam gameserver account with logon token 'A1C0029Fxxxxxxxxxxxxxxxxxxxxxxxx'
srcds_linux: ../server-plugin/Code/Players/NczPlayerManager.h:343: PlayerHandler::iterator::operator SlotStatus() const: Assertion `IsIteratorValid ()' failed.

Program received signal SIGABRT, Aborted.
0xf7fda9f2 in ?? () from /lib/ld-linux.so.2
(gdb) bt
#0  0xf7fda9f2 in ?? () from /lib/ld-linux.so.2
#1  0xf7dc6977 in raise () from /lib32/libc.so.6
#2  0xf7dc7f49 in abort () from /lib32/libc.so.6
#3  0xf7dbfa27 in ?? () from /lib32/libc.so.6
#4  0xf7dbfaab in __assert_fail () from /lib32/libc.so.6
#5  0xec7d4051 in PlayerHandler::iterator::operator SlotStatus (this=0xffffa014)
    at ../server-plugin/Code/Players/NczPlayerManager.h:343
#6  0xec7d2eb2 in CNoCheatZPlugin::ClientPutInServer (this=0x8fcbdc0, pEntity=0xee2bb030, playername=0xb987190 "GOTV")
    at Code/plugin.cpp:443
#7  0xf69b8985 in CServerPlugin::ClientPutInServer(edict_t*, char const*) () from /mnt/p/home/steam/csgo/bin/engine.so
#8  0xf699b70c in CGameClient::ActivatePlayer() () from /mnt/p/home/steam/csgo/bin/engine.so
#9  0xf68a91a4 in CBaseServer::CreateFakeClient(char const*) () from /mnt/p/home/steam/csgo/bin/engine.so
#10 0xf69b1531 in SV_ActivateServer() () from /mnt/p/home/steam/csgo/bin/engine.so
#11 0xf692630a in Host_NewGame(char*, char*, bool, bool, bool, char const*, char const*) ()
   from /mnt/p/home/steam/csgo/bin/engine.so
#12 0xf692d407 in CHostState::State_NewGame() () from /mnt/p/home/steam/csgo/bin/engine.so
#13 0xf692dabb in CHostState::FrameUpdate(float) () from /mnt/p/home/steam/csgo/bin/engine.so
#14 0xf692daf9 in HostState_Frame(float) () from /mnt/p/home/steam/csgo/bin/engine.so
#15 0xf69ca66a in CEngine::Frame() () from /mnt/p/home/steam/csgo/bin/engine.so
#16 0xf69c75f6 in CDedicatedServerAPI::RunFrame() () from /mnt/p/home/steam/csgo/bin/engine.so
#17 0xf784cc2d in RunServerIteration(bool) () from ./bin/dedicated.so
#18 0xf784ccb8 in RunServer(bool) () from ./bin/dedicated.so
#19 0xf69c76ed in CModAppSystemGroup::Main() () from /mnt/p/home/steam/csgo/bin/engine.so
#20 0xf6b17e70 in CAppSystemGroup::Run() () from /mnt/p/home/steam/csgo/bin/engine.so
#21 0xf69c88b7 in CDedicatedServerAPI::ModInit(ModInfo_t&) () from /mnt/p/home/steam/csgo/bin/engine.so
#22 0xf784cd94 in CDedicatedAppSystemGroup::Main() () from ./bin/dedicated.so
#23 0xf7870740 in CAppSystemGroup::Run() () from ./bin/dedicated.so
#24 0xf787196e in CSteamApplication::Main() () from ./bin/dedicated.so
#25 0xf7870740 in CAppSystemGroup::Run() () from ./bin/dedicated.so
#26 0xf7812d73 in main () from ./bin/dedicated.so
#27 0x080486f9 in main ()

**Comment by askovpen** [comment]
startup ok :-)
