### ISSUE TITLE
Observer CBaseHandle gives invalid index in SetTransmit

### ISSUE THREAD

**Issue by askovpen** [L-EARN/NoCheatZ-4#67]
```
[STEAM_1:1:122269664] Pure server: file: GAME\models/items/medkit_large.phy ( 1 4006 fa6 ) could not open file to hash ( benign for now ) : 2eeed9771c3023f2da9b9efbad818c16 :

[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  16046.4 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0bb070 -> pEntity->classname:player -> clientname:╰\/ǺĽÊŖǺ†, args:spec_mode 3)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  16046.6 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0bb070 -> pEntity->classname:player -> clientname:╰\/ǺĽÊŖǺ†, args:spec_mode 3)
[STEAM_1:1:122269664] Pure server: file: GAME\models/weaponf/crashz.vvd ( 1 503168 7ad80 ) could not open file to hash ( benign for now ) : 580471d79e3b9ab4124c16d8fb3d5cf3 :

[STEAM_1:1:122269664] Pure server: file: GAME\models/items/healthkit.mdl ( 1 1504 5e0 ) could not open file to hash ( benign for now ) : 83f4a58bebca82d7353e354e8d0ed98f :

[STEAM_1:1:122269664] Pure server: file: GAME\materials/akami/weapons/rubyaxe/t004.vmt ( 1 338 152 ) could not open file to hash ( benign for now ) : 23542f33b42b853a64e836b9f7496760 :

[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  16047.1 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0bb050 -> pEntity->classname:player -> clientname:◆ǺĻĚ$Ĥà◇, args:+lookatweapon 16)
[STEAM_1:1:122269664] Pure server: file: GAME\models/items/medkit_small.dx90.vtx ( 1 11598 2d4e ) could not open file to hash ( benign for now ) : c43b2fb78fe662f987701e5be603233b :

[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  16047.3 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0bb050 -> pEntity->classname:player -> clientname:◆ǺĻĚ$Ĥà◇, args:-lookatweapon 16)
[STEAM_1:1:122269664] Pure server: file: GAME\materials/models/weaponf/v_models/knife_ct/knife.vtf ( 1 4194848 4000d0 ) could not open file to hash ( benign for now ) : 14adbbfca2ef8b223815ea94d7185989 :

[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  16047.5 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0bb050 -> pEntity->classname:player -> clientname:◆ǺĻĚ$Ĥà◇, args:+lookatweapon 16)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  16047.6 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0bb050 -> pEntity->classname:player -> clientname:◆ǺĻĚ$Ĥà◇, args:-lookatweapon 16)
[STEAM_1:1:122269664] Pure server: file: GAME\materials/models/weapons/caleon1/screwdriver/black.vmt ( 1 85 55 ) could not open file to hash ( benign for now ) : 16aa65d6375c3167d7a98f4fb5883eef :

Player ♤GR@4ツ : total_bhopCount = 1
[STEAM_1:1:122269664] Pure server: file: GAME\models/items/medkit_small.mdl ( 1 3140 c44 ) could not open file to hash ( benign for now ) : 531334dc27920f7df94e463053bab44c :

[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  16048.1 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0bb050 -> pEntity->classname:player -> clientname:◆ǺĻĚ$Ĥà◇, args:+lookatweapon 16)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  16048.2 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0bb050 -> pEntity->classname:player -> clientname:◆ǺĻĚ$Ĥà◇, args:-lookatweapon 16)
[STEAM_1:1:122269664] Pure server: file: GAME\materials/models/weapons/caleon1/screwdriver/metal.vmt ( 1 85 55 ) could not open file to hash ( benign for now ) : cb7f7291e65cb265ed9debcdfe0161e5 :

[STEAM_1:1:122269664] Pure server: file: GAME\models/weapons/caleon1/screwdriver/v_knife_screwdriver.mdl ( 1 16936 4228 ) could not open file to hash ( benign for now ) : 548d8383bdc4af0271b4dcdae812c42f :

[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  16048.5 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0bb050 -> pEntity->classname:player -> clientname:◆ǺĻĚ$Ĥà◇, args:+lookatweapon 16)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  16048.6 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0bb050 -> pEntity->classname:player -> clientname:◆ǺĻĚ$Ĥà◇, args:-lookatweapon 16)
[STEAM_1:1:122269664] Pure server: file: GAME\materials/models/weaponf/v_models/tridagger/steel/tridagger.vmt ( 1 651 28b ) could not open file to hash ( benign for now ) : 3ecb372a015afb93c749b90c16224cda :

[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  16049 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0bb050 -> pEntity->classname:player -> clientname:◆ǺĻĚ$Ĥà◇, args:+lookatweapon 16)
[STEAM_1:1:122269664] Pure server: file: GAME\models/weapons/v_gongfu.vvd ( 1 120832 1d800 ) could not open file to hash ( benign for now ) : 854d4625214da520d7464ca82905efca :

[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  16049.1 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0bb050 -> pEntity->classname:player -> clientname:◆ǺĻĚ$Ĥà◇, args:-lookatweapon 16)
[STEAM_1:1:122269664] Pure server: file: GAME\models/weapons/caleon1/screwdriver/v_knife_screwdriver.vvd ( 1 63360 f780 ) could not open file to hash ( benign for now ) : 6aadbda981dacfd26255454e4fbba4f5 :

[STEAM_1:1:122269664] Pure server: file: GAME\models/weapons/v_gongfu.mdl ( 1 60380 ebdc ) could not open file to hash ( benign for now ) : c345bb739ef4fca319fa36e727d610e1 :

[STEAM_1:1:122269664] Pure server: file: GAME\materials/models/weapons/minecraft_pickaxe/minecraft_pick_final.vtf ( 1 175320 2ab88 ) could not open file to hash ( benign for now ) : 2371ceef6a46a89697a4eea6ffb0a59a :

[STEAM_1:1:122269664] Pure server: file: GAME\models/items/cs_gift.phy ( 1 1929 789 ) could not open file to hash ( benign for now ) : c8bad4caa7f59e01e7fd1a9130ccb260 :

[STEAM_1:1:122269664] Pure server: file: GAME\materials/models/items/mushroom/lightwrap.vtf ( 1 960 270 ) could not open file to hash ( benign for now ) : 5f3f5c21fa54eb69ea88e3dcf3782282 :

[STEAM_1:1:122269664] Pure server: file: GAME\models/items/medkit_small.vvd ( 1 39168 9900 ) could not open file to hash ( benign for now ) : 1e06f90fe4299ea0b989c2494dab97eb :

[STEAM_1:1:122269664] Pure server: file: GAME\materials/models/items/cs_gift.vmt ( 1 68 44 ) could not open file to hash ( benign for now ) : 1ccdb6521aca2c6959c20efb3c979663 :

[STEAM_1:1:122269664] Pure server: file: GAME\materials/akami/weapons/rubyaxe/t006.vmt ( 1 338 152 ) could not open file to hash ( benign for now ) : 765dfc98565dd360f91bb230b824b9ed :

[STEAM_1:1:122269664] Pure server: file: GAME\materials/models/items/mushroom/stem.vmt ( 1 205 cd ) could not open file to hash ( benign for now ) : 01a4f2f000cf412b4eb04d54f0698854 :

Player ◆ǺĻĚ$Ĥà◇ : total_bhopCount = 13
Testing ConCommand say of ✪NIk0
Bypassed ConCommand say of ✪NIk0
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  16051.4 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0bb070 -> pEntity->classname:player -> clientname:╰\/ǺĽÊŖǺ†, args:spec_mode 4)
srcds_linux: ../server-plugin/Code/Players/NczPlayerManager.h:270: PlayerHandler::iterator::operator bool() const: Assertion `IsIteratorValid ()' failed.

Program received signal SIGABRT, Aborted.
0xf7fda9f2 in ?? () from /lib/ld-linux.so.2
(gdb) bt
#0  0xf7fda9f2 in ?? () from /lib/ld-linux.so.2
#1  0xf7dc6977 in raise () from /lib32/libc.so.6
#2  0xf7dc7f49 in abort () from /lib32/libc.so.6
#3  0xf7dbfa27 in ?? () from /lib32/libc.so.6
#4  0xf7dbfaab in __assert_fail () from /lib32/libc.so.6
#5  0xec7df00d in PlayerHandler::iterator::operator bool (this=0xffffa000) at ../server-plugin/Code/Players/NczPlayerManager.h:270
#6  0xec7ea45b in WallhackBlocker::RT_SetTransmitCallback (this=0x9003ab0, sender_player=..., receiver_player=...) at Code/Systems/Blockers/WallhackBlocker.cpp:159
#7  0xec7ded2d in SetTransmitHookListener::RT_nSetTransmit (This=0xb5e0068, pInfo=0xfc0cf58, bAlways=false) at Code/Hooks/SetTransmitHookListener.cpp:73
#8  0xf2f81ee0 in CServerGameEnts::CheckTransmit(CCheckTransmitInfo*, unsigned short const*, int) () from /mnt/p/home/steam/csgo/csgo/bin/server.so
#9  0xf69b771b in SV_ComputeClientPacks(int, CGameClient**, CFrameSnapshot*) () from /mnt/p/home/steam/csgo/bin/engine.so
#10 0xf69b402e in CGameServer::SendClientMessages(bool) () from /mnt/p/home/steam/csgo/bin/engine.so
#11 0xf69b43b1 in SV_SendClientUpdates(bool, bool) () from /mnt/p/home/steam/csgo/bin/engine.so
#12 0xf69b44e0 in SV_Frame(bool) () from /mnt/p/home/steam/csgo/bin/engine.so
#13 0xf692308e in _Host_RunFrame_Server(bool) () from /mnt/p/home/steam/csgo/bin/engine.so
#14 0xf6923d2c in _Host_RunFrame(float) () from /mnt/p/home/steam/csgo/bin/engine.so
#15 0xf6924468 in Host_RunFrame(float) () from /mnt/p/home/steam/csgo/bin/engine.so
#16 0xf692d714 in CHostState::State_Run(float) () from /mnt/p/home/steam/csgo/bin/engine.so
#17 0xf692d9e6 in CHostState::FrameUpdate(float) () from /mnt/p/home/steam/csgo/bin/engine.so
#18 0xf692daf9 in HostState_Frame(float) () from /mnt/p/home/steam/csgo/bin/engine.so
#19 0xf69ca66a in CEngine::Frame() () from /mnt/p/home/steam/csgo/bin/engine.so
#20 0xf69c75f6 in CDedicatedServerAPI::RunFrame() () from /mnt/p/home/steam/csgo/bin/engine.so
#21 0xf784cc2d in RunServerIteration(bool) () from ./bin/dedicated.so
#22 0xf784ccb8 in RunServer(bool) () from ./bin/dedicated.so
#23 0xf69c76ed in CModAppSystemGroup::Main() () from /mnt/p/home/steam/csgo/bin/engine.so
#24 0xf6b17e70 in CAppSystemGroup::Run() () from /mnt/p/home/steam/csgo/bin/engine.so
#25 0xf69c88b7 in CDedicatedServerAPI::ModInit(ModInfo_t&) () from /mnt/p/home/steam/csgo/bin/engine.so
#26 0xf784cd94 in CDedicatedAppSystemGroup::Main() () from ./bin/dedicated.so
#27 0xf7870740 in CAppSystemGroup::Run() () from ./bin/dedicated.so
#28 0xf787196e in CSteamApplication::Main() () from ./bin/dedicated.so
#29 0xf7870740 in CAppSystemGroup::Run() () from ./bin/dedicated.so
#30 0xf7812d73 in main () from ./bin/dedicated.so
#31 0x080486f9 in main ()
```

**Comment by askovpen** [comment]
```
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19872.6 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff050 -> pEntity->classname:player -> clientname:LavkaЧехова, args:open_buymenu )
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19874.6 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff030 -> pEntity->classname:player -> clientname:✪The area of infection, args:+lookatweapon 16)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19874.7 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff050 -> pEntity->classname:player -> clientname:LavkaЧехова, args:buy sg556 17)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19874.7 DEBUG : VirtualTableHook : function 0xF2DE29F0 at 0xF3496844 replaced by 0xEC7EBBD0.
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19874.8 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff030 -> pEntity->classname:player -> clientname:✪The area of infection, args:-lookatweapon 16)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19875.1 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff030 -> pEntity->classname:player -> clientname:✪The area of infection, args:+lookatweapon 16)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19875.4 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff030 -> pEntity->classname:player -> clientname:✪The area of infection, args:-lookatweapon 16)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19875.5 DEBUG : CNoCheatZPlugin::ClientPutInServer (pEntity:0xee0ff060 -> pEntity->classname:, playername:Suprotec залей.) (Was already connected: Yes)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19875.5 DEBUG : CNoCheatZPlugin::ClientActive (pEntity:0xee0ff060 -> pEntity->classname:player -> clientname:Suprotec залей.)
PutClientInServer: no info_player_start on level
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19875.5 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff060 -> pEntity->classname:player -> clientname:Suprotec залей., args:VModEnable 1)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19875.9 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff050 -> pEntity->classname:player -> clientname:LavkaЧехова, args:buy flashbang 28)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19876.2 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff050 -> pEntity->classname:player -> clientname:LavkaЧехова, args:buy hegrenade 29)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19876.5 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff050 -> pEntity->classname:player -> clientname:LavkaЧехова, args:buy smokegrenade 30)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19876.8 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff050 -> pEntity->classname:player -> clientname:LavkaЧехова, args:close_buymenu )
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19877.2 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff030 -> pEntity->classname:player -> clientname:✪The area of infection, args:+lookatweapon 16)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19877.2 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff050 -> pEntity->classname:player -> clientname:LavkaЧехова, args:+lookatweapon 16)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19877.3 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff030 -> pEntity->classname:player -> clientname:✪The area of infection, args:-lookatweapon 16)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19877.3 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff050 -> pEntity->classname:player -> clientname:LavkaЧехова, args:-lookatweapon 16)
Player ✪The area of infection : total_bhopCount = 22
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19881.8 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff060 -> pEntity->classname:player -> clientname:Suprotec залей., args:joingame )
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19881.8 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff060 -> pEntity->classname:player -> clientname:Suprotec залей., args:jointeam 0 1)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19883 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff060 -> pEntity->classname:player -> clientname:Suprotec залей., args:spec_scoreboard )
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19886.3 DEBUG : Player ✪The area of infection flash alpha 255.000000, duration 3.741604
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19891.9 DEBUG : Player ✪The area of infection flash alpha 255.000000, duration 0.788677
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19891.9 DEBUG : Player LavkaЧехова flash alpha 255.000000, duration 0.983075
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19891.9 DEBUG : Player Suprotec залей. flash alpha 255.000000, duration 1.967188
L 07/12/2016 - 16:00:12: [csgo_country_v2.smx] 9 round end, 6:3(4) - 8 - de_dust2_night
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19903.5 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff030 -> pEntity->classname:player -> clientname:✪The area of infection, args:+lookatweapon 16)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19903.8 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff030 -> pEntity->classname:player -> clientname:✪The area of infection, args:-lookatweapon 16)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19903.9 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff030 -> pEntity->classname:player -> clientname:✪The area of infection, args:+lookatweapon 16)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19904.1 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff030 -> pEntity->classname:player -> clientname:✪The area of infection, args:-lookatweapon 16)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19904.3 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff030 -> pEntity->classname:player -> clientname:✪The area of infection, args:+lookatweapon 16)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19904.4 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff030 -> pEntity->classname:player -> clientname:✪The area of infection, args:-lookatweapon 16)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19906.3 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff050 -> pEntity->classname:player -> clientname:LavkaЧехова, args:spec_scoreboard )
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19907.8 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff030 -> pEntity->classname:player -> clientname:✪The area of infection, args:open_buymenu )
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19908.2 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff050 -> pEntity->classname:player -> clientname:LavkaЧехова, args:open_buymenu )
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19909.1 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff030 -> pEntity->classname:player -> clientname:✪The area of infection, args:buy flashbang 28)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19909.4 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff030 -> pEntity->classname:player -> clientname:✪The area of infection, args:close_buymenu )
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19910.5 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff050 -> pEntity->classname:player -> clientname:LavkaЧехова, args:buy ak47 15)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19911.7 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff050 -> pEntity->classname:player -> clientname:LavkaЧехова, args:buy decoy 27)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19912.1 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff050 -> pEntity->classname:player -> clientname:LavkaЧехова, args:close_buymenu )
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19912.8 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff060 -> pEntity->classname:player -> clientname:Suprotec залей., args:autobuy "m4a1 ak47 famas galil mp7 nova primammo secammo defuser vesthelm vest")
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19916.7 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff050 -> pEntity->classname:player -> clientname:LavkaЧехова, args:+lookatweapon 16)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19916.8 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff050 -> pEntity->classname:player -> clientname:LavkaЧехова, args:-lookatweapon 16)
L 07/12/2016 - 16:00:50: [csgo_country_v2.smx] 10 round end, 6:4(4) - 9 - de_dust2_night
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19936.7 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff050 -> pEntity->classname:player -> clientname:LavkaЧехова, args:+lookatweapon 16)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19936.8 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff050 -> pEntity->classname:player -> clientname:LavkaЧехова, args:-lookatweapon 16)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19937.3 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff030 -> pEntity->classname:player -> clientname:✪The area of infection, args:spec_mode 3)
[NoCheatZ v4-beta-r1-190-g8da3ecf-debug]  19937.5 DEBUG : CNoCheatZPlugin::ClientCommand (pEntity:0xee0ff030 -> pEntity->classname:player -> clientname:✪The area of infection, args:spec_mode 3)
srcds_linux: ../server-plugin/Code/Players/NczPlayerManager.h:270: PlayerHandler::iterator::operator bool() const: Assertion `IsIteratorValid ()' failed.

Program received signal SIGABRT, Aborted.
0xf7fda9f2 in ?? () from /lib/ld-linux.so.2
(gdb) bt
#0  0xf7fda9f2 in ?? () from /lib/ld-linux.so.2
#1  0xf7dc6977 in raise () from /lib32/libc.so.6
#2  0xf7dc7f49 in abort () from /lib32/libc.so.6
#3  0xf7dbfa27 in ?? () from /lib32/libc.so.6
#4  0xf7dbfaab in __assert_fail () from /lib32/libc.so.6
#5  0xec7ec00d in PlayerHandler::iterator::operator bool (this=0xffffa000) at ../server-plugin/Code/Players/NczPlayerManager.h:270
#6  0xec7f745b in WallhackBlocker::RT_SetTransmitCallback (this=0x9003ab0, sender_player=..., receiver_player=...) at Code/Systems/Blockers/WallhackBlocker.cpp:159
#7  0xec7ebd2d in SetTransmitHookListener::RT_nSetTransmit (This=0x9bce2a0, pInfo=0xb83c338, bAlways=false) at Code/Hooks/SetTransmitHookListener.cpp:73
#8  0xf2f81ee0 in CServerGameEnts::CheckTransmit(CCheckTransmitInfo*, unsigned short const*, int) () from /mnt/p/home/steam/csgo/csgo/bin/server.so
#9  0xf69b771b in SV_ComputeClientPacks(int, CGameClient**, CFrameSnapshot*) () from /mnt/p/home/steam/csgo/bin/engine.so
#10 0xf69b402e in CGameServer::SendClientMessages(bool) () from /mnt/p/home/steam/csgo/bin/engine.so
#11 0xf69b43b1 in SV_SendClientUpdates(bool, bool) () from /mnt/p/home/steam/csgo/bin/engine.so
#12 0xf69b44e0 in SV_Frame(bool) () from /mnt/p/home/steam/csgo/bin/engine.so
#13 0xf692308e in _Host_RunFrame_Server(bool) () from /mnt/p/home/steam/csgo/bin/engine.so
#14 0xf6923d2c in _Host_RunFrame(float) () from /mnt/p/home/steam/csgo/bin/engine.so
#15 0xf6924468 in Host_RunFrame(float) () from /mnt/p/home/steam/csgo/bin/engine.so
#16 0xf692d714 in CHostState::State_Run(float) () from /mnt/p/home/steam/csgo/bin/engine.so
#17 0xf692d9e6 in CHostState::FrameUpdate(float) () from /mnt/p/home/steam/csgo/bin/engine.so
#18 0xf692daf9 in HostState_Frame(float) () from /mnt/p/home/steam/csgo/bin/engine.so
#19 0xf69ca66a in CEngine::Frame() () from /mnt/p/home/steam/csgo/bin/engine.so
#20 0xf69c75f6 in CDedicatedServerAPI::RunFrame() () from /mnt/p/home/steam/csgo/bin/engine.so
#21 0xf784cc2d in RunServerIteration(bool) () from ./bin/dedicated.so
#22 0xf784ccb8 in RunServer(bool) () from ./bin/dedicated.so
#23 0xf69c76ed in CModAppSystemGroup::Main() () from /mnt/p/home/steam/csgo/bin/engine.so
#24 0xf6b17e70 in CAppSystemGroup::Run() () from /mnt/p/home/steam/csgo/bin/engine.so
#25 0xf69c88b7 in CDedicatedServerAPI::ModInit(ModInfo_t&) () from /mnt/p/home/steam/csgo/bin/engine.so
#26 0xf784cd94 in CDedicatedAppSystemGroup::Main() () from ./bin/dedicated.so
#27 0xf7870740 in CAppSystemGroup::Run() () from ./bin/dedicated.so
#28 0xf787196e in CSteamApplication::Main() () from ./bin/dedicated.so
#29 0xf7870740 in CAppSystemGroup::Run() () from ./bin/dedicated.so
#30 0xf7812d73 in main () from ./bin/dedicated.so
#31 0x080486f9 in main ()
